language: python

matrix:
  include:
    - python: 2.7 
    - python: 3.6

before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda;
- export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH";
- hash -r;
- conda config --set always_yes yes --set changeps1 no;
- conda create -y -q -n test_cq -c pythonocc -c oce -c conda-forge -c dlr-sc pythonocc-core=0.18 pyparsing mock;
- source ~/miniconda/bin/activate test_cq;

install:
- python setup.py install

script:
- python runtests.py

branches:
  except:
  - pythonocc
  - 2_0_branch