language: python
before_install:
- sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
- sudo apt-get update -qq
install:
- sudo apt-get install -y freecad freecad-doc
- gcc --version
- g++ --version
- python ./setup.py install
- pip install -r requirements-dev.txt
- pip install travis-sphinx
- pip install sphinx_rtd_theme

# Install miniconda, cf https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
#- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- alias conda=~/miniconda/bin/conda
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -y -q -n freecad_cq3 -c freecad -c conda-forge freecad=0.17 python=3.6 pyparsing
- source ~/miniconda/bin/activate freecad_cq3
- python setup.py install
- unalias conda

script:
# py3 part
- export FREECAD_LIB=~/miniconda/envs/freecad_cq3/lib/
- python runtests.py
- source deactivate
- unset FREECAD_LIB
#py2 part
- python runtests.py
- coverage run --source=cadquery ./runtests.py
- travis-sphinx build --nowarn --source=doc

after_success:
- coveralls
- travis-sphinx deploy

branches:
  except:
  - pythonocc
  - 2_0_branch

  deploy:
  provider: pypi
  user: dcowden
  password:
    secure: aP02wBbry1j3hYG/w++siF1lk26teuRQlPAx1c+ec8fxUw+bECa2HbPQHcIvSXB5N6nc6P3L9LjHt9ktm+Dn6FLJu3qWYNGAZx9PTn24ug0iAmB+JyNrsET3nK6WUKR1XpBqvjKgdpukd1Hknh2FSzYoyUvFWH9/CovITCFN3jo=
  on:
    tags: true
