shallow_clone: true

platform:
    - x64

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          MINICONDA_DIRNAME: C:\Miniconda37-x64
          PYTHON_VERSION: 3.7
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          MINICONDA_DIRNAME: C:\Miniconda38-x64
          PYTHON_VERSION: 3.8
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          MINICONDA_DIRNAME: C:\Miniconda38-x64
          PYTHON_VERSION: 3.9
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          PYTHON_VERSION: 3.7
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          PYTHON_VERSION: 3.8
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          PYTHON_VERSION: 3.9
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
          PYTHON_VERSION: 3.7
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
          PYTHON_VERSION: 3.8
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
          PYTHON_VERSION: 3.9

    ANACONDA_TOKEN:
        secure: $(anaconda_token)

init:
    - cmd: set "PATH=%MINICONDA_DIRNAME%;%MINICONDA_DIRNAME%\\Scripts;%PATH%"
    - sh: if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu" ]]; then
              OS=Linux ;
          else
              OS=MacOSX ;
              brew install gsed
              export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH";
          fi ;
          curl -sL https://repo.anaconda.com/miniconda/Miniconda3-latest-$OS-x86_64.sh > miniconda.sh
    - sh: bash miniconda.sh -b -p $HOME/miniconda;
    - sh: export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH";

install:
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Python version substitution in environment.yml for Linux/MacOS, update the Python version to be replaced when we raise the minimum Python version
    - sh: sed -i 's/python>=3.6/python=$PYTHON_VERSION/g' environment.yml
    # Python version substitution in environment.yml for Windows, update the Python version to be replaced when we raise the minimum Python version
    - pwsh: ((Get-Content -path environment.yml -Raw) -replace 'python>=3.6',"python=$env:PYTHON_VERSION") | Set-Content -Path environment.yml
    - sh: cat environment.yml
    - conda env create -f environment.yml
    - activate cadquery
    - pip install git+https://github.com/CadQuery/OCP-stubs.git@7.5.1

build: false

test_script:
    - black . --diff --check
    - mypy cadquery
    - pytest -v --cov

on_success:
    - codecov
