shallow_clone: true

platform:
    - x64

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          MINICONDA_DIRNAME: C:\Miniconda37-x64
          PYTHON_VERSION: 3.7
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          MINICONDA_DIRNAME: C:\Miniconda38-x64
          PYTHON_VERSION: 3.8
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          MINICONDA_DIRNAME: C:\Miniconda38-x64
          PYTHON_VERSION: 3.9
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          PYTHON_VERSION: 3.7
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          PYTHON_VERSION: 3.8
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          PYTHON_VERSION: 3.9
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
          PYTHON_VERSION: 3.7
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
          PYTHON_VERSION: 3.8
        - APPVEYOR_BUILD_WORKER_IMAGE: macOS
          PYTHON_VERSION: 3.9

    ANACONDA_TOKEN:
        secure: $(anaconda_token)

init:
    - cmd: set "PATH=%MINICONDA_DIRNAME%;%MINICONDA_DIRNAME%\\Scripts;%PATH%"
    - sh: if [[ "$APPVEYOR_BUILD_WORKER_IMAGE" == "Ubuntu" ]]; then
              OS=Linux ;
          else
              OS=MacOSX ;
          fi ;
          curl -sL https://repo.anaconda.com/miniconda/Miniconda3-latest-$OS-x86_64.sh > miniconda.sh
    - sh: bash miniconda.sh -b -p $HOME/miniconda;
    - sh: export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH";

install:
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - pwsh: ((Get-Content -path environment.yml -Raw) -replace 'python>=3.6',"python=$PYTHON_VERSION") | Set-Content -Path environment.yml
    - sh: sed -i 's/python>=3.6/python=$PYTHON_VERSION/g' environment.yml
    - pwsh: type environment.yml
    - conda env create -f environment.yml
    - activate cadquery
    #- cmd: conda install -c conda-forge -c defaults -c cadquery python=%PYTHON_VERSION%
    #- sh: conda install -c conda-forge -c defaults -c cadquery python=$PYTHON_VERSION
    #- pip install black=19.10b0
    #- cmd: conda install python=%PYTHON_VERSION%
    #- sh: conda install python=$PYTHON_VERSION
    - pip install git+https://github.com/CadQuery/OCP-stubs.git@7.5.1
    #- pip install mypy
    #- pip install pytest
    #- pip install pytest-cov
    #- pip install path
    #- pip install docutils
    #- pip install codecov

build: false

test_script:
    - black . --diff --check
    - mypy cadquery
    - pytest -v --cov

on_success:
    - codecov
