trigger:
  branches:
    include:
      - master
      - refs/tags/*

pr:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: CadQuery/conda-packages
      endpoint: CadQuery

parameters:
  - name: minor
    type: object
    default:
      - 8
      - 9
      - 10

jobs:
- ${{ each minor in parameters.minor }}:
  - template: conda-build.yml@templates
    parameters:
      name: Linux_3_${{minor}}
      vmImage: 'ubuntu-18.04'
      py_maj: 3
      py_min: ${{minor}}
      conda_bld: 3.21.6

  - template: conda-build.yml@templates
    parameters:
      name: macOS_3_${{minor}}
      vmImage: 'macOS-10.15'
      py_maj: 3
      py_min: ${{minor}}
      conda_bld: 3.21.6

  - template: conda-build.yml@templates
    parameters:
      name: Windows_3_${{minor}}
      vmImage: 'vs2017-win2016'
      py_maj: 3
      py_min: ${{minor}}
      conda_bld: 3.21.6
